# Generated by Django 4.1.6 on 2023-03-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_alter_departamento_anombrecorto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNombreEmpleado', models.CharField(max_length=50, verbose_name='aNombreEmpleado')),
                ('aApellidoEmpleado', models.CharField(max_length=50, verbose_name='aApellidoEmpleado')),
                ('aTrabajo', models.CharField(choices=[('0', 'contador'), ('1', 'administrador'), ('2', 'economista'), ('4', 'otro')], max_length=1, verbose_name='aDepeartamento')),
                ('aDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
