# Generated by Django 4.1.6 on 2023-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='aHabilidades',
            field=models.ManyToManyField(to='empleados.habilidades'),
        ),
    ]
