# Generated by Django 4.1.6 on 2023-03-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNombre', models.CharField(max_length=50, verbose_name='aNombre')),
                ('aNombreCorto', models.CharField(max_length=5, verbose_name='aNombreCorto')),
                ('nActivo', models.BooleanField(default=False, verbose_name='nActivo')),
            ],
        ),
    ]
