# Generated by Django 4.1.6 on 2023-03-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_anombrecorto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-aNombre'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('aNombre', 'aNombreCorto')},
        ),
    ]
